name: Publish Docker Image
on:
  push:
    branches:
      - master

jobs:
  publish:
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build and publish
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7 . --push --tag hugoatease/gaia:latest
