name: Publish Docker Image
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create dockerx builder
        run: docker buildx create --use --name=gaia
      - name: build and publish
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7 . --push --tag hugoatease/gaia:latest
